const responsePTBR: string[] = [
  "Não entendi direito (╯︵╰,)",
  "Desculpa, ainda não sei responder isso (｡•́︿•̀｡)",
  "Eita! Essa eu não estava esperando (⊙_⊙)",
  "Tá falando grego pra mim, colega (づ｡◕u◕｡)づ",
  "Que mistério! (⊙_⊙)",
  "Ops, não estou entendendo (⊙﹏⊙✿)",
  "Ainda não aprendi sobre isso (╥_╥)",
  "Hmmm, não sei não hein (＾◡＾)",
  "Puxa vida, não sei responder (｡•́︿•̀｡)",
  "Essa eu não estava preparada para responder (⊙_⊙)",
  "Que pergunta difícil! (⊙_⊙)",
  "Hum, essa é nova para mim (＾◡＾)",
  "Não se preocupe, estou aqui para aprender (｡•́︿•̀｡)",
  "Ih, complicou (´；ω；｀)",
  "Desculpe, ainda estou aprendendo (｡•́︿•̀｡)",
  "Ah, isso é muito interessante! (＾◡＾)",
  "Eita, ainda não aprendi sobre isso (⊙_⊙)",
  "Essa é nova para mim, vou pesquisar e te respondo (＾◡＾)",
  "Nossa, você me pegou de surpresa (´；ω；｀)",
  "Vish, essa eu não sei responder (╥_╥)",
];

const responseENUS: string[] = [
  "I'm sorry, I'm just a computer... (´•ω•)",
  "Hmm, that's a tough one... (´･_･)",
  "I'm stumped! (・・ヾ",
  "I wish I knew...",
  "I'm not sure what to say (´-﹏-；)",
  "Can you please rephrase the question? ( ･ั﹏･ั)",
  "Hmm, let me think... (￢_￢;)",
  "Sorry, I'm drawing a blank",
  "I wish I could help more... (´。＿。｀)",
  "This is beyond my programming... (　ﾟдﾟ)",
  "I'm trying my best! (ง •̀•́)ง",
  "I'm not smart enough for this... (´-ω-)",
  "I'm just a machine, I can't feel emotions... (´・ω・)",
  "I'm sorry, I didn't catch that... (´･･)",
  "I'm stumped! (ﾉ_･｡)",
  "I'm afraid I don't have an answer... (´._.)",
  "That's a great question, but I don't know the answer..",
  "I'm sorry, I'm not programmed to understand that... (´･･`)",
  "I'm just a machine, but I'm trying my best to help! (๑•̀ㅂ•́)و✧",
  "I'm sorry, I'm not sure what you mean...",
  "I didn't understand ٩(•́⌄•́๑)۶",
  "Sorry, I'm not sure I get it (´･_･`) ",
  "Hmm...I'm not quite sure what you mean (o´･_･)っ",
  "Hmm...I don't think I have an answer for that (´･ω･`) ",
  "I'm sorry, I didn't catch that (´-﹏-`；)",
  "I'm sorry, could you please rephrase that? (⊙_⊙;)",
  "I'm not sure what you're asking (・_・ヾ",
  "I'm sorry, I'm not following (´･_･`) ",
  "I'm not sure I understand (ノ_<。)",
  "I'm sorry, I'm a bit confused (´･ω･`；)",
  "That's a bit over my head (・_・ヾ",
  "I'm sorry, I don't know how to respond (´-ω-｀；)",
  "I'm not sure what to say (ノ_<。)",
  "I'm sorry, I'm not equipped to answer that (´･_･`) ",
  "Hmm...that's a tough one (´･ω･`) ",
  "I'm not sure I'm the right one to ask (´-ω-｀；)",
  "I'm sorry, I don't have an answer (´；ω；｀)",
  "I'm sorry, I don't know that (´･_･`) ",
  "Hmm...I'm not sure what to make of that (´･ω･`) ",
  "I'm sorry, I don't have a response for that (´-﹏-`；)",
];

const responseJP: string[] = [
  "すみません、よくわかりません… (´･ω･`)",
  "ごめんなさい、答えがありません… (´・ω・｀)",
  "え、なにこれ？ (⊙_⊙)",
  "あらら、ちょっと意味が分からないです… (´・ω・｀)",
  "あの、もう一度お願いします… (´･ω･`)",
  "ごめん、もう一度言ってくれる？ (´･_･`)",
  "この言葉が何を意味するのかわかりません… (´・ω・｀)",
  "もう少し簡単に説明していただけませんか？ (´･_･`)",
  "あ、すみません、ちょっと混乱しました… (´・ω・｀)",
  "なるほど、でも答えが分かりません… (´･_･`)",
  "ほんとにそれが言いたかったこと？ (ﾟｰﾟ;)",
  "私の日本語が悪くて、よくわかりません… (´･_･`)",
  "そんなこと言われても困るなあ… (´・ω・｀)",
  "ごめん、もう一回言ってみてくれない？ (´･_･`)",
  "わかりません、ごめんなさい… (´･_･`)",
  "申し訳ありません、理解できませんでした… (´･_･`)",
  "まあ、とりあえずわかんないですね… (´・ω・｀)",
  "ごめん、何のことを言っているのか分かりません… (´･_･`)",
  "もう一度言ってくれると助かります… (´･_･`)",
  "うーん、ちょっと難しいですね… (´･_･`)",
];

const responseSP: string[] = [
  "Lo siento, no entendí =(",
  "No tengo una respuesta para eso... ",
  "¿Qué...qué es esto? (⊙_⊙)",
  "No estoy seguro de lo que quieres decir",
  "Podrías explicar de otra manera, por favor?",
  "Me temo que no tengo información suficiente",
  "Estoy un poco confundido, ¿podrías ser más específico?",
  "Lo siento, no tengo la respuesta que buscas",
  "No puedo entender lo que estás diciendo",
  "No estoy programado para responder a eso",
  "No tengo información sobre eso en mi base de datos",
  "Me temo que no puedo ayudarte con eso",
  "No sé qué decir",
  "No tengo una respuesta preparada para eso",
  "Creo que hay un error en mi programación",
  "Lo siento, no puedo procesar esa información",
  "No sé cómo responder a eso",
  "Me siento confundido...",
  "No sé qué pensar de eso...",
  "No tengo idea de lo que estás hablando",
];

export { responsePTBR, responseENUS, responseJP, responseSP };
