name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Aumentei o timeout para 15 minutos para dar tempo suficiente para a instalação das dependências

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Versão do Node que deseja instalar
          cache: npm

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '17' # Versão do Java que deseja instalar

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6' # Versão do Gradle que deseja instalar

      - name: Install Capacitor and Add Android Platform
        run: |
          npm install -g @capacitor/cli
          npm install
          npx cap update
          npx cap add android

      - name: Give execute permission to gradlew
        run: chmod +x ./android/gradlew
        
      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Install NPM Dependencies
        run: npm ci

      - name: Decode keystore
        run: |
          mkdir -p ./android/keystore/
          echo "${{ secrets.COOKIE_KEY }}" | base64 -d > ./android/keystore/release.keystore
        
      - name: Build APK
        run: |
          npx cap build android --keystorepath "keystore/release.keystore" --keystorepass $KEYSTOREPASS --keystorealiaspass $KEYSTOREALIASPASS --keystorealias $KEYSTOREALIAS --androidreleasetype APK
          rm -rf ./android/keystore/release.keystore
          mv ./android/app/build/outputs/apk/release/app-release-signed.apk ./android/app/build/outputs/apk/release/SEGES+.apk
          rm -rf ./android/app/build/outputs/apk/release/app-release-unsigned.apk

        env:
          KEYSTOREPASS: cookieukw
          KEYSTOREALIASPASS: cookieukw
          KEYSTOREALIAS: cookieukw

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
