name: Build

on:
  push:
    branches:
      - main

jobs:
  setup-capacitor-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and initialize Capacitor
        run: |
          npm install
          npx cap init android

      - name: Install Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Print Java version
        run: java -version

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Decode Keystore from Base64
        run: echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore
     
      - name: Find debug keystore
        run: |
          debug_keystore_path="$HOME/cookie.keystore"
          if [ -f "$debug_keystore_path" ]; then
            echo "Debug Keystore: $debug_keystore_path"
          else
            echo "Debug Keystore not found."
          fi

      - name: Give execute permission to gradlew
        run: chmod +x ./android/gradlew

      - name: Build the React application
        run: npm run build

      - name: Sync files with Capacitor
        run: npx cap sync

      - name: Verify Capacitor platform
        run: npx cap ls

      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Build Android APK
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
          ANDROID_KEY_PASSWORD: cookieukw
        run: |
           npx cap build android --keystorepath=$ANDROID_KEYSTORE_PATH --keystorepass=$ANDROID_KEYSTORE_PASSWORD --keystorealias=$ANDROID_KEY_ALIAS --keystorealiaspass=$ANDROID_KEY_PASSWORD --androidreleasetype=APK
     
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
            ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }}
