name: BuildVexMobile

on:
  release:
    types:
      - created

jobs:
  setup-capacitor-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          npx cap init
  
      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17
          
      - name: Print Java version
        run: java -version

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
        
      - name: Give execute permission to gradlew
        run: |
          chmod +x ./android/gradlew
      - name: Decode Keystore from Base64
        run: echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore

     # - name: Create Debug Keystore
        #run: |
        #  keytool -genkeypair -v -keystore ${{ github.workspace }}/cookiekeystore -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -alias androiddebugkey
 
      - name: Find Debug Keystore
        run: |
         debug_keystore_path="${{ github.workspace }}/cookie.keystore"
         if [ -f "$debug_keystore_path" ]; then
         echo "Debug Keystore: $debug_keystore_path"
         else
         echo "Debug Keystore not found."
         fi
         
      - name: Check Keystore
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
        run: |
          keytool -list -v -keystore $ANDROID_KEYSTORE_PATH -storepass $ANDROID_KEYSTORE_PASSWORD -alias $ANDROID_KEY_ALIAS

      - name: Build the React Application
        run: npm run build

      - name: Sync files
        run: npx cap sync

      - name: Verify Capacitor Platform
        run: npx cap ls
        
      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Build Android
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          SIGNING_STORE_PASSWORD: cookieukw
          SIGNING_KEY_ALIAS: cookieukw
          SIGNING_KEY_PASSWORD: cookieukw
         
        run: |
          cd android
          ./gradlew bundleRelease
          ./gradlew assembleRelease 
           cd app/build/outputs/
           for apk in $(find . -name "*.apk"); do
             apksigner sign --v2-signing-enabled true --ks $ANDROID_KEYSTORE_PATH --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD --ks-key-alias $ANDROID_KEY_ALIAS --key-pass pass:$ANDROID_KEY_PASSWORD --out "${apk%.apk}-signed.apk" "$apk"
           done
          
 
# -PRELEASE_STORE_FILE=$ANDROID_KEYSTORE_PATH -PRELEASE_STORE_PASS=$SIGNING_KEY_PASSWORD -PRELEASE_ALIAS=$SIGNING_KEY_ALIAS -PRELEASE_KEY_PASS=$SIGNING_STORE_PASSWORD

         
          
        # Comente ou remova as linhas npx cap buil
        # npx cap build android --keystorepath=$ANDROID_KEYSTORE_PATH --keystorepass=$ANDROID_KEYSTORE_PASSWORD --keystorealias=$ANDROID_KEY_ALIAS --keystorealiaspass=$ANDROID_KEY_PASSWORD --androidreleasetype=AAB
        # npx cap build android --keystorepath=$ANDROID_KEYSTORE_PATH --keystorepass=$ANDROID_KEYSTORE_PASSWORD --keystorealias=$ANDROID_KEY_ALIAS --keystorealiaspass=$ANDROID_KEY_PASSWORD --androidreleasetype=APK


      #- name: Upload Release Build to Artifacts
       
        #uses: actions/upload-artifact@v3
        #with:
         # name: release-artifacts
          #path: |
           # ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
            #${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk

  #    - name: Release with Notes
   #     uses: softprops/action-gh-release@v1
    #    with:
     #     files: |
      #      ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
       #     ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk

        #env:
         # GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }}

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
                ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
                ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }} 
