name: BuildVexMobile

on:
  push:
    branches:
      - main

jobs:
  setup-capacitor-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          npx cap init

      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17
          
      - name: Print Java version
        run: java -version

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
        
      - name: Give execute permission to gradlew
        run: |
          chmod +x ./android/gradlew

      - name: Decode Keystore from Base64
        run: echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore

      - name: Find Debug Keystore
        run: |
         debug_keystore_path="${{ github.workspace }}/cookie.keystore"
         if [ -f "$debug_keystore_path" ]; then
         echo "Debug Keystore: $debug_keystore_path"
         else
         echo "Debug Keystore not found."
         fi

      - name: Check Keystore
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
        run: |
          keytool -list -v -keystore $ANDROID_KEYSTORE_PATH -storepass $ANDROID_KEYSTORE_PASSWORD -alias $ANDROID_KEY_ALIAS


      - name: Build the React Application
        run: npm run build

      - name: Sync files
        run: npx cap sync

      - name: Verify Capacitor Platform
        run: npx cap ls
        
      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Build Android
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
          ANDROID_KEY_PASSWORD: cookieukw
        run: |
         cd ${{ github.workspace }}/android
          ./gradlew bundleRelease --stacktrace 
          apksigner sign --v2-signing-enabled true --ks $ANDROID_KEYSTORE_PATH --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD --ks-key-alias $ANDROID_KEY_ALIAS --key-pass pass:$ANDROID_KEY_PASSWORD --out "app-release-signed.aab" app-release.aab
          ./gradlew assembleRelease --stacktrace
          echo "Conteúdo do diretório de APKs:"
          ls -al app/build/outputs/apk/release
          cd app/build/outputs/apk/release
          for apk in *.apk; do
            apksigner sign --v2-signing-enabled true --ks $ANDROID_KEYSTORE_PATH --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD --ks-key-alias $ANDROID_KEY_ALIAS --key-pass pass:$ANDROID_KEY_PASSWORD --out "${apk%.apk}-signed.apk" $apk
          done

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
                ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
                ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk

        env:
          GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }}
