name: BuildVexMobile

on:
  release:
    types:
      - created

jobs:
  setup-capacitor-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
          
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Print Java version
        run: java -version

      - name: Give execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.COOKIE_KEY }}
        run: |
          echo $ENCODED_STRING | base64 -di > $RUNNER_TEMP/cookie.jks

      - name: Build the React Application
        run: npm run build

      - name: Sync files
        run: npx cap sync

      - name: Verify Capacitor Platform
        run: npx cap ls
        
      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Build prod
        run: ./android/gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: cookieukw
          SIGNING_KEY_PASSWORD: cookieukw
          SIGNING_STORE_PASSWORD: cookieukw

      - name: Verify signature
        run: |
          for apk in android/app/build/outputs/bundle/release/*.aab android/app/build/outputs/apk/release/*.apk; do
            echo "Verifying signature of file: $apk"
            apksigner verify --verbose "$apk"
          done

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            android/app/build/outputs/bundle/release/*.aab
            android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }}
