name: BuildVexMobile

on:
  push:
    branches:
      - main
jobs:
  check-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Decode Keystore from Base64
        run: echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore

      - name: Check Keystore
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
        run: |
          keytool -list -v -keystore $ANDROID_KEYSTORE_PATH -storepass $ANDROID_KEYSTORE_PASSWORD -alias $ANDROID_KEY_ALIAS
